name       : keymapp
version    : 1.3.2
release    : 1
source     :
    - https://oryx.nyc3.cdn.digitaloceanspaces.com/keymapp/keymapp-1.3.2.tar.gz : f6e9a2f50596486d16df0f5dede470b591d4adaa889e4a896c4f8b91d9f74d4f
homepage   : https://www.zsa.io/flash
license    : PROPRIETARY
component  : system.utils
summary    : A live visual reference for your ZSA keyboard layout, right when you need it.
description: |
    Keymapp allows you to view your keyboard's layout right on your screen, in real-time.
    When you switch a layer, Keymapp's display updates to show the keys active on this layer.
install    : |
    install -Dm00755 $workdir/keymapp $installdir/usr/bin/keymapp
    install -Dm00644 $workdir/icon.png $installdir/usr/share/icons/hicolor/1024x1024/apps/keymapp.png
    install -Dm00644 $pkgfiles/icons/512/keymapp.png $installdir/usr/share/icons/hicolor/512x512/apps/keymapp.png
    install -Dm00644 $pkgfiles/icons/256/keymapp.png $installdir/usr/share/icons/hicolor/256x256/apps/keymapp.png
    install -Dm00644 $pkgfiles/icons/128/keymapp.png $installdir/usr/share/icons/hicolor/128x128/apps/keymapp.png
    install -Dm00644 $pkgfiles/icons/64/keymapp.png $installdir/usr/share/icons/hicolor/64x64/apps/keymapp.png
    install -Dm00644 $pkgfiles/icons/48/keymapp.png $installdir/usr/share/icons/hicolor/48x48/apps/keymapp.png
    install -Dm00644 $pkgfiles/icons/32/keymapp.png $installdir/usr/share/icons/hicolor/32x32/apps/keymapp.png
    install -Dm00644 $pkgfiles/icons/24/keymapp.png $installdir/usr/share/icons/hicolor/24x24/apps/keymapp.png
    install -Dm00644 $pkgfiles/icons/16/keymapp.png $installdir/usr/share/icons/hicolor/16x16/apps/keymapp.png
    install -Dm00644 $pkgfiles/keymapp.desktop $installdir/usr/share/applications/keymapp.desktop
    install -Dm00644 $pkgfiles/50-zsa.rules $installdir/etc/udev/rules.d/50-zsa.rules
