name       : ulauncher
version    : 5.9.9
release    : 21
source     :
    - https://github.com/Ulauncher/Ulauncher/releases/download/v6.0.0-beta18/ulauncher-6.0.0-beta18.tar.gz : 65441a2712631562c1b7903378498ac0308a7f368b3199098be6296f46608449
homepage   : https://ulauncher.io/
license    : GPL-3.0-or-later
component  : desktop
summary    : Linux Application Launcher
description: |
    Ulauncher is a fast application launcher for Linux. It's is written in Python, using GTK+.
builddeps  :
    - python-build
    - python-distutils-extra
    - python-installer
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - keybinder
    - libwebkit-gtk
    - python-gobject
    - python-inotify
    - python-levenshtein
    - python-pygithub
    - python-websocket-client
    - python3-dbus
    - pyxdg
build      : |
    %python3_setup
install    : |
    %python3_install

    # We don't have wmctrl because it is DOA
    rm -f $installdir/usr/bin/ulauncher-toggle
